### ISSUE TITLE
Functions 'I2C4_WriteReg' and 'I2C4_ReadReg': argument order different between definitions and declarations

### ISSUE THREAD

**Issue by escherstair** [STMicroelectronics/stm32h735g-dk#1]
For the two functions in the title of the issue, the argument order is different between declaration and definition (`MemAddSize` and `Reg` swapped)

`I2C4_WriteReg` declaration
https://github.com/STMicroelectronics/stm32h735g-dk/blob/23be129947f0290f3888ecfbdda893642213d535/stm32h735g_discovery_bus.c#L178
`I2C4_WriteReg` definition
https://github.com/STMicroelectronics/stm32h735g-dk/blob/23be129947f0290f3888ecfbdda893642213d535/stm32h735g_discovery_bus.c#L840

`I2C4_ReadReg` declaration
https://github.com/STMicroelectronics/stm32h735g-dk/blob/23be129947f0290f3888ecfbdda893642213d535/stm32h735g_discovery_bus.c#L179
`I2C4_ReadReg` definition
https://github.com/STMicroelectronics/stm32h735g-dk/blob/23be129947f0290f3888ecfbdda893642213d535/stm32h735g_discovery_bus.c#L857

**Comment by ASELSTM** [comment]
ST Internal Reference: 127120

**Comment by ALABSTM** [comment]
Fixed in commit af6455b36f92bcc6507ccb822ad0615b38605268

**Comment by ALABSTM** [comment]
Hi @escherstair,

I hope you are doing well. Just to let you know this issue has been fixed. Thank you for your patience and thank you again for having reported.

With regards,
